#!/bin/bash

# Bash config
echo "Bash config"
cp .bash_aliases ~/.bash_aliases
cp .bashrc ~/.bashrc
cp .profile ~/.profile

# GTK config
echo "GTK config"
cp gtk.css ~/.config/gtk-3.0/gtk.css

# Git config
echo "Git config"
cp .gitconfig ~/.gitconfig

# Vim config
echo "Vim config"
mkdir -p ~/.vim
cp vimrc ~/.vim/vimrc

echo "Installing Vim Plug"
curl -fLso ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Generic utils
echo "Generic utils"
cp -r utils/ ~

# Done
echo "Done"
