#!/bin/bash

MOUSE_ID=$(xinput | \grep "Mouse" | sed 's/.*id=\([0-9]\+\).*/\1/')

for ID in $MOUSE_ID; do
    xinput set-prop $ID "libinput Scroll Method Enabled" 0, 0, 0
    xinput set-prop $ID "libinput Button Scrolling Button" 2
done
